MVC_DynamicMenu/Models/AddNewUnavailability.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_DynamicMenu.Models
{
    public class AddNewUnavailability
    {
        [Key]
        public int UID { get; set; }
        public string Worker { get; set; }
        public string Is_all_day { get; set; }
        public string Start_time { get; set; }
        public string End_time { get; set; }
        public string Recurrance { get; set; }
        public string Comment { get; set; }

    }
}

MVC_DynamicMenu/Controllers/UnavailabilityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC_DynamicMenu.Models;
using MVC_DynamicMenu.Repo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_DynamicMenu.Controllers
{
    public class UnavailabilityController : Controller
    {
        private readonly UnavailabilityRepo _c = null;

        public UnavailabilityController(UnavailabilityRepo c)
        {
            _c = c;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ViewResult AddNewUnavailability()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddNewUnavailability(AddNewUnavailability model)
        {
            _c.AddNewUnavailability(model);
            return RedirectPermanent("/Unavailability/GetAllUnavailability");
        }
        [HttpGet]
        public ViewResult GetAllUnavailability()
        {
            HttpContext.Session.SetString("availability", _c.GetPatients());
            List<AddNewUnavailability> UA = _c.GetAllUnavailability();
            List<MainUnavailabilityTb> ua = new List<MainUnavailabilityTb>();

            foreach (var item in UA)
            {
                MainUnavailabilityTb ua1 = new MainUnavailabilityTb
                {
                    Worker = item.Worker,
                    Start_time = item.Start_time,
                    Recurrance = item.Recurrance,
                    Is_all_day = item.Is_all_day,
                    End_time = item.End_time,
                    Comment = item.Comment,
                    Approved = "Approved",
                    End_Recurrance = "",
                    UnavailabilityID = item.UID
                };
                ua.Add(ua1);
            }
            return View(ua);
        }
        [HttpGet]
        public ViewResult UpdateUnavailability(int id)
        {
            AddNewUnavailability UN = _c.GetUnavailabilityById(id);
            return View(UN);
        }

        [HttpGet]
        public ViewResult ViewtUnavailability(int id)
        {
            AddNewUnavailability UN = _c.GetUnavailabilityById(id);
            return View(UN);
        }

        [HttpPost]
        public ActionResult UpdateUnavailability(AddNewUnavailability model)
        {
            _c.UpdateUnavailability(model);
            return RedirectPermanent("/Unavailability/GetAllUnavailability");
        }

        [Route("Unavailability/DeleteUnavailability/{id:int}")]
        public ActionResult DeleteUnavailability(int id)
        {
            _c.DeleteUnavailability(id);
            return RedirectPermanent("/Unavailability/GetAllUnavailability");
        }
    }
}

MVC_DynamicMenu/Views/Unavailability/AddNewUnavailability.cshtml
@model AddNewUnavailability
@using Newtonsoft.Json;
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "AddNewClient";
    List<Patient> cli = JsonConvert.DeserializeObject<List<Patient>>(Context.Session.GetString("availability"));
}
<head>
    <link href="~/css/Addfile.css" rel="stylesheet" />
</head>
<div class="container">
    <header class="header">
        <h1 id="title" class="text-center">Add New Unavailability</h1>
        <p id="description" class="description text-center">

        </p>
    </header>





    <form asp-action="AddNewUnavailability" id="survey-form">
        <div class="form-group">

            <div class="row">
                <div class="procolumn">

                </div>
                <div class="procolumn">
                    <h6>Worker</h6>
                    <br />
                    <br />
                    <h6>Is All Day?</h6>
                    <br />

                    <label for="dateofbirth">Start Date</label>
                    <br />
                    <label for="dateofbirth">End Date</label>
                    <br />
                    <h6>Recurrance</h6>
                    <br />
                    <h6>Comment</h6>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <div>
                        <div style="float:left"><button type="submit" class="btn btn-secondary" onClick="return false;">Cancel</button></div>
                    </div>
                </div>


                <div class="pro3column">
                    <select id="dropdown" asp-for="Worker" class="form-control" required>
                        @*<option disabled selected value>Gendere</option>*@
                        <option value="Pasan Wijesuriya">Pasan Wijesuriya</option>
                    </select>
                    <br />
                    <select id="dropdown" asp-for="Is_all_day" class="form-control" required>
                        <option value="Yes">Yes</option>
                        <option value="No">No</option>
                    </select>
                    <br />
                    <input type="date" asp-for="Start_time" id="dateofbirth">
                    <br />
                    <input type="date" asp-for="End_time" id="dateofbirth">
                    <br />
                    <select id="dropdown" asp-for="Recurrance" class="form-control" required>
                        @*<option disabled selected value>Gendere</option>*@
                        <option value="none">--none--</option>
                        <option value="Daily">Daily</option>
                        <option value="Weekly">Weekly</option>
                        <option value="Monthly">Monthly</option>
                        <option value="Yearly">Yearly</option>
                    </select>
                    <br />
                    <textarea id="comments"
                              class="input-textarea"
                              asp-for="Comment"></textarea>
                    <br />
                    <br />
                    <br />
                    <div>
                        <div style="float:right"><button type="submit" class="btn btn-primary">Update</button></div>
                    </div>
                </div>
                <div class="procolumn">

                </div>
            </div>



        </div>


        <script type="text/javascript">
            const projectName = 'survey-form';

        </script>
    </form>
</div>

MVC_DynamicMenu/Views/Unavailability/GetAllUnavailability.cshtml
@model List<MainUnavailabilityTb>
@{
    ViewData["Title"] = "Home page";
}
<head>
    <link href="~/css/Addfile.css" rel="stylesheet" />
</head>
<div class="container">
    <header class="header">
        <h1 id="title" class="text-center">Add New Unavailability</h1>
        <p id="description" class="description text-center">

        </p>
    </header>
    <div class="text-right">
        <input onkeyup="myFunction()" id="myInput" type="text" name="text" class="search" placeholder="Search here!">

        <button type="button" onclick='window.location.href = "/Unavailability/AddNewUnavailability"' class="btn btn-primary">+Add Unavailabilty</button>
    </div>
    <br />

    <form id="survey-form">


        <div class="row" style="overflow-x:auto;">
            <div class="col-md-12">
                <table class="table badge-light" id="myTable">
                    <thead>
                        <tr>
                            <th>Worker</th>
                            <th>Is All Day?</th>
                            <th>Start Time</th>
                            <th>End Time</th>
                            <th>Recurrance</th>
                            <th>End Recurrance By</th>
                            <th>Comment</th>
                            <th>Approved</th>

                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Worker</td>
                            <td>@item.Is_all_day</td>
                            <td>@item.Start_time</td>
                            <td>@item.End_time</td>
                            <td>@item.Recurrance</td>
                            <td>@item.End_Recurrance</td>
                            <td>@item.Comment</td>
                            <td>@item.Approved</td>
                            <td>
                                <a asp-controller="Unavailability" asp-action="ViewtUnavailability" asp-route-id="@item.UnavailabilityID">View</a>
                                <a asp-controller="Unavailability" asp-action="UpdateUnavailability" asp-route-id="@item.UnavailabilityID">Update</a>
                                <a asp-controller="Unavailability" asp-action="DeleteUnavailability" asp-route-id="@item.UnavailabilityID">Delete</a>
                            </td>
                        </tr>
                    }


                </table>
            </div>
        </div>

        <script type="text/javascript">
            const projectName = 'survey-form';

        </script>
        @section Scripts{
            <script>
                function myFunction() {
                    var input, filter, table, tr, td, i, txtValue;
                    input = document.getElementById("myInput");
                    filter = input.value.toUpperCase();
                    table = document.getElementById("myTable");
                    tr = table.getElementsByTagName("tr");
                    for (i = 0; i < tr.length; i++) {
                        td = tr[i].getElementsByTagName("td")[1];
                        if (td) {
                            txtValue = td.textContent || td.innerText;
                            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                tr[i].style.display = "";
                            } else {
                                tr[i].style.display = "none";
                            }
                        }
                    }
                }
            </script>


        }
    </form>


</div>

MVC_DynamicMenu/Views/Unavailability/UpdateUnavailability.cshtml
@model AddNewUnavailability
@using Newtonsoft.Json;
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "AddNewClient";
 
}
<head>
    <link href="~/css/Addfile.css" rel="stylesheet" />
</head>
<div class="container">
    <header class="header">
        <h1 id="title" class="text-center">Add New Unavailability</h1>
        <p id="description" class="description text-center">

        </p>
    </header>





    <form asp-action="UpdateUnavailability" id="survey-form">
        <div class="form-group">

            <div class="row">
                <div class="procolumn">

                </div>
                <div class="procolumn">
                    <h6>Worker</h6>
                    <br />
                    <br />
                    <h6>Is All Day?</h6>
                    <br />

                    <label for="dateofbirth">Start Date</label>
                    <br />
                    <label for="dateofbirth">End Date</label>
                    <br />
                    <h6>Recurrance</h6>
                    <br />
                    <h6>Comment</h6>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <div>
                        <div style="float:left"><button type="submit" class="btn btn-secondary" onClick="return false;">Cancel</button></div>
                    </div>
                </div>


                <div class="pro3column">
                    <select id="dropdown" asp-for="Worker" class="form-control" required>
                        @*<option disabled selected value>Gendere</option>*@
                        <option value="Pasan Wijesuriya">Pasan Wijesuriya</option>
                    </select>
                    <input type="hidden" asp-for="UID"/>
                    <br />
                    <select id="dropdown" asp-for="Is_all_day" class="form-control" required>
                        <option value="Yes">Yes</option>
                        <option value="No">No</option>
                    </select>
                    <br />
                    <input type="date" asp-for="Start_time" id="dateofbirth">
                    <br />
                    <input type="date" asp-for="End_time" id="dateofbirth">
                    <br />
                    <select id="dropdown" asp-for="Recurrance" class="form-control" required>
                        @*<option disabled selected value>Gendere</option>*@
                        <option value="none">--none--</option>
                        <option value="Daily">Daily</option>
                        <option value="Weekly">Weekly</option>
                        <option value="Monthly">Monthly</option>
                        <option value="Yearly">Yearly</option>
                    </select>
                    <br />
                    <textarea id="comments"
                              class="input-textarea"
                              asp-for="Comment"></textarea>
                    <br />
                    <br />
                    <br />
                    <div>
                        <div style="float:right"><button type="submit" class="btn btn-primary">Update</button></div>
                    </div>
                </div>
                <div class="procolumn">

                </div>
            </div>



        </div>


        <script type="text/javascript">
            const projectName = 'survey-form';

        </script>
    </form>
</div>

MVC_DynamicMenu/Views/Unavailability/ViewtUnavailability.cshtml
@model AddNewUnavailability
@using Newtonsoft.Json;
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "AddNewClient";
  
}
<head>
    <link href="~/css/Addfile.css" rel="stylesheet" />
</head>
<div class="container">
    <header class="header">
        <h1 id="title" class="text-center">Add New Unavailability</h1>
        <p id="description" class="description text-center">

        </p>
    </header>





    <form asp-action="" id="survey-form">
        <div class="form-group">

            <div class="row">
                <div class="procolumn">

                </div>
                <div class="procolumn">
                    <h6>Worker</h6>
                    <br />
                    <br />
                    <h6>Is All Day?</h6>
                    <br />

                    <label for="dateofbirth">Start Date</label>
                    <br />
                    <label for="dateofbirth">End Date</label>
                    <br />
                    <h6>Recurrance</h6>
                    <br />
                    <h6>Comment</h6>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />

                </div>


                <div class="pro3column">
                    <select id="dropdown" asp-for="Worker" class="form-control" required>
                        @*<option disabled selected value>Gendere</option>*@
                        <option value="Pasan Wijesuriya">Pasan Wijesuriya</option>
                    </select>
                    <br />
                    <select id="dropdown" asp-for="Is_all_day" class="form-control" required>
                        <option value="Yes">Yes</option>
                        <option value="No">No</option>
                    </select>
                    <br />
                    <input type="date" asp-for="Start_time" id="dateofbirth">
                    <br />
                    <input type="date" asp-for="End_time" id="dateofbirth">
                    <br />
                    <select id="dropdown" asp-for="Recurrance" class="form-control" required>
                        @*<option disabled selected value>Gendere</option>*@
                        <option value="none">--none--</option>
                        <option value="Daily">Daily</option>
                        <option value="Weekly">Weekly</option>
                        <option value="Monthly">Monthly</option>
                        <option value="Yearly">Yearly</option>
                    </select>
                    <br />
                    <textarea id="comments"
                              class="input-textarea"
                              asp-for="Comment"></textarea>
                    <br />
                    <br />
                    <br />
                
                </div>
                <div class="procolumn">

                </div>
            </div>



        </div>


        <script type="text/javascript">
            const projectName = 'survey-form';

        </script>
    </form>
</div>