MVC_DynamicMenu/Controllers/SLESController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC_DynamicMenu.Models;
using MVC_DynamicMenu.Repo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_DynamicMenu.Controllers
{
    public class SLESController : Controller
    {
        private readonly AddNewSLESProgressRepo _context;

        public SLESController(AddNewSLESProgressRepo context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public ViewResult AddNewSLES()
        {
            return View();
        }
        public void setSession(int id)
        {
            var newUser = _context.getUserById(id);
            HttpContext.Session.SetString("loggedname", newUser.Clients);
        }
        [HttpPost]

        public ActionResult AddNewSLES(AddNewSLESProgress SLES)
        {
            _context.AddNewSLES(SLES);
            return RedirectPermanent("/SLES/ShowALLSLESProgresses");
        }

        [HttpGet]
        public ViewResult ShowALLSLESProgresses()
        {
            HttpContext.Session.SetString("sles", _context.GetPatients());
            List<AddNewSLESProgress> newSLES = _context.AddNewSELES();
            List<SLESProgress> newSles = new List<SLESProgress>();

            foreach (var item in newSLES)
            {
                SLESProgress newSles1 = new SLESProgress
                {
                    Client = item.Client,
                    EntryDate = item.EntryDate,
                    LastUpdate = item.EntryDate,
                    Reference = item.ClientID,
                    Unit = "Counseling"
                };
                newSles.Add(newSles1);
            }
            return View(newSles);
        }

        [HttpGet]
        public ViewResult UpdateSLES(int id)
        {
            AddNewSLESProgress sles = _context.getSlesById(id);
            return View(sles);
        }

        [HttpGet]
        public ViewResult ViewSLES(int id)
        {
            AddNewSLESProgress sles = _context.getSlesById(id);
            return View(sles);
        }

        [Route("/AddNewSLESProgress/DeleteSLES/{id:int}")]
        public ActionResult DeleteSLES(int id)
        {
            _context.DeleteSLES(id);
            return RedirectPermanent("/SLES/ShowALLSLESProgresses");
        }

        [HttpPost]
        public ActionResult UpdateSLES(AddNewSLESProgress model)
        {
            _context.UpdateSLES(model);
            return RedirectPermanent("/SLES/ShowALLSLESProgresses");
        }

    }
}

MVC_DynamicMenu/Views/SLES/AddNewSLES.cshtml
@model AddNewSLESProgress
@using Newtonsoft.Json;
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "AddNewClient";
    List<Patient> cli = JsonConvert.DeserializeObject<List<Patient>>(Context.Session.GetString("sles"));
    string loggeduser = Context.Session.GetString("loggedname");
}
<head>
    <link href="~/css/Addfile.css" rel="stylesheet" />
</head>
<div class="container">
    <header class="header">
        <h1 id="title" class="text-center">Add New SLES Progress</h1>
        <p id="description" class="description text-center">

        </p>
    </header>
    <form asp-action="AddNewSLES" id="survey-form">
        <div class="form-group">
            <label id="name-label" asp-for="Client">Participant</label>
            <select class="form-control" asp-for="Client" placeholder="Pick a Name">
                @foreach (var item in cli)
                {
                    <option value="@item.Full_Name">@item.Full_Name</option>

                }

            </select>
        </div>
        @*Date Start*@
        <label asp-for="EntryDate">Entry Date</label>
        <input type="date" asp-for="EntryDate" id="dateofbirth">

        @*Hierarchy Start*@
        <div class="form-group">
            <p>Hierarchy</p>
            <select id="dropdown" asp-for="Hierarchy" class="form-control" required>
                @*<option disabled selected value>Select current role</option>*@
                <option value="ACT_Springfield_Evergreen">ACT Springfield Evergreen</option>
                <option value="NWS_Demo_Region">NWS Demo Region</option>
                <option value="NSW_Demo_Region_A_Unit_1_3">NSW Demo Region A Unit 1 3</option>
                <option value="NSW_Demo_Region_2_Unit_2_1_A">NSW Demo Region 2 Unit 2 1 A</option>
                <option value="QLD_Region_4_Bridging_Famillies">QLD Region 4 Bridging Famillies</option>
                <option value="QLD_Region_Younger_parents_program">QLD Region Younger parents program</option>
                <option value="NWS_Eiver_Dischange_review">NWS Eiver Dischange review</option>
            </select>
        </div>

        <label asp-for="Date">Date</label>
        <input type="date" asp-for="Date" id="dateofbirth">
        <button type="button" class="accordion">Type of Contact</button>
        <div class="panel">
            <div class="form-group">


                <h6>Type Of Contact</h6>
                <label>
                    <input asp-for="TypeOfContact"
                           value="Yes"
                           type="radio"
                           class="input-radio"
                           checked />Yes
                </label>
                <label>
                    <input asp-for="TypeOfContact"
                           value="No"
                           type="radio"
                           class="input-radio" />No
                </label>

            </div>

        </div>

        <button type="button" class="accordion">Activity</button>
        <div class="panel">
            <h6>Activity</h6>
            <textarea id="comments"
                      class="input-textarea"
                      asp-for="Activity"></textarea>

            <div class="form-group">


                <h6>Any Barrierss Identified</h6>
                <label>
                    <input asp-for="AnyBarrierssIdentified"
                           value="Yes"
                           type="radio"
                           class="input-radio"
                           checked />Yes
                </label>
                <label>
                    <input asp-for="AnyBarrierssIdentified"
                           value="No"
                           type="radio"
                           class="input-radio" />No
                </label>

            </div>

            <h6>If yes list barriers identifieed</h6>
            <textarea id="comments"
                      class="input-textarea"
                      asp-for="If_yes_list_barriers_identifieed"></textarea>

            <h6>Step taken to Address beriers</h6>
            <textarea id="comments"
                      class="input-textarea"
                      asp-for="Step_taken_to_Address_beriers"></textarea>

            <h6>Duration</h6>
            <label id="name-label" asp-for="Duration">Duration</label>
            <input type="text"
                   asp-for="Duration"
                   id="name"
                   class="form-control"
                   required />

            <div class="form-group">
                <p>Completion & Sign-off</p>
                <label id="name-label" asp-for="StaffName">Staff Member Name</label>
                <input type="text"
                       asp-for="StaffName"
                       id="name"
                       value="@loggeduser"
                   readonly
                       class="form-control"
                       placeholder="Select Staff"
                       required />
            </div>
        </div>
        <button type="submit" id="submit" class="submit-button">
            Submit
        </button>

        <script type="text/javascript">
            const projectName = 'survey-form';

        </script>

        <script>
            $(document).ready(function () {
                $('select').selectize({
                    sortField: 'text'
                });
            });

        </script>
    </form>
</div>

MVC_DynamicMenu/Views/SLES/ShowALLSLESProgresses.cshtml
@model List<SLESProgress>
@{
    ViewData["Title"] = "Home page";
}
<head>
    <link href="~/css/Addfile.css" rel="stylesheet" />
</head>
<div class="container">
    <header class="header">
        <div class="text-right">
            <button type="button" onclick='window.location.href = "/SLES/AddNewSLES"' class="btn btn-primary">+New Entry</button>
        </div>
        <h1 id="title" class="text-center">SLES Progress Note</h1>
        <p id="description" class="description text-center">

        </p>
    </header>
    <form id="survey-form">
        <div class="form-group">
            <label id="name-label" for="name">Select Participant</label>
            <input type="text"
                   name="name"
                   id="myInput"
                   class="form-control"
                   placeholder="Enter name"
                   onkeyup="myFunction()"
                   required />
        </div>

        @*Date Start*@
        <label for="dateofbirth"></label>
        <input type="date" name="dateofbirth" id="dateofbirth">
        @*Date Start*@
        <label for="dateofbirth"></label>
        <input type="date" name="dateofbirth" id="dateofbirth">

        @*Hierarchy Start*@
        <div class="form-group">
            <p>Please Select a State</p>
            <select id="dropdown" name="role" class="form-control" required>
                @*<option disabled selected value>Select current role</option>*@
                <option value="student">ACT</option>
                <option value="job">NSW</option>
                <option value="learner">VIC</option>
                <option value="student">QLD</option>
                <option value="job">SA</option>
                <option value="learner">WA</option>
                <option value="job">TAS</option>
                <option value="learner">NTA</option>
            </select>
        </div>

        <div class="row" style="overflow-x:auto;">
            <div class="col-md-12">
                <table class="table badge-light">
                    <thead>
                        <tr>
                            <th>Reference</th>
                            <th>Participant</th>
                            <th>Unity</th>
                            <th>Entry Data</th>
                            <th>Last Uplod</th>
                            <th>Action</th>
                        </tr>
                    </thead> @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Reference</td>
                            <td>@item.Client</td>
                            <td>@item.Unit</td>
                            <td>@item.EntryDate</td>
                            <td>@item.EntryDate</td>
                            <td>
                                <a asp-controller="SLES" asp-action="ViewSLES" asp-route-id="@item.Reference">View</a>
                                <a asp-controller="SLES" asp-action="UpdateSLES" asp-route-id="@item.Reference">Update</a>
                                <a asp-controller="SLES" asp-action="DeleteSLES" asp-route-id="@item.Reference">Delete</a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>

        <script type="text/javascript">
            const projectName = 'survey-form';

        </script>
        @section Scripts{
            <script>
                function myFunction() {
                    var input, filter, table, tr, td, i, txtValue;
                    input = document.getElementById("myInput");
                    filter = input.value.toUpperCase();
                    table = document.getElementById("myTable");
                    tr = table.getElementsByTagName("tr");
                    for (i = 0; i < tr.length; i++) {
                        td = tr[i].getElementsByTagName("td")[1];
                        if (td) {
                            txtValue = td.textContent || td.innerText;
                            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                tr[i].style.display = "";
                            } else {
                                tr[i].style.display = "none";
                            }
                        }
                    }
                }
            </script>
        }
    </form>

MVC_DynamicMenu/Views/SLES/UpdateSLES.cshtml
@model MVC_DynamicMenu.Models.AddNewSLESProgress
@{
    ViewData["Title"] = "Home page";
}
<head>
    <link href="~/css/Addfile.css" rel="stylesheet" />
</head>
<div class="container">
    <header class="header">
        <h1 id="title" class="text-center">Add New SLES Progress</h1>
        <p id="description" class="description text-center">

        </p>
    </header>
    <form asp-action="UpdateSLES" id="survey-form">
        <div class="form-group">
            <label id="name-label" asp-for="Client">Participant</label>
            <input type="text"
                   asp-for="Client"
                   id="name"
                   class="form-control"
                   placeholder="Enter your name"
                   required />


        </div>
        <input type="hidden" asp-for="ClientID" />
        @*Date Start*@
        <label asp-for="EntryDate">Entry Date</label>
        <input type="date" asp-for="EntryDate" id="dateofbirth">

        @*Hierarchy Start*@
        <div class="form-group">
            <p>Hierarchy</p>
            <select id="dropdown" asp-for="Hierarchy" class="form-control" required>
                @*<option disabled selected value>Select current role</option>*@
                <option value="ACT_Springfield_Evergreen">ACT Springfield Evergreen</option>
                <option value="NWS_Demo_Region">NWS Demo Region</option>
                <option value="NSW_Demo_Region_A_Unit_1_3">NSW Demo Region A Unit 1 3</option>
                <option value="NSW_Demo_Region_2_Unit_2_1_A">NSW Demo Region 2 Unit 2 1 A</option>
                <option value="QLD_Region_4_Bridging_Famillies">QLD Region 4 Bridging Famillies</option>
                <option value="QLD_Region_Younger_parents_program">QLD Region Younger parents program</option>
                <option value="NWS_Eiver_Dischange_review">NWS Eiver Dischange review</option>
            </select>
        </div>

        <label asp-for="Date">Date</label>
        <input type="date" asp-for="Date" id="dateofbirth">
        <button type="button" class="accordion">Type of Contact</button>
        <div class="panel">
            <div class="form-group">


                <h6>Type Of Contact</h6>
                <label>
                    <input asp-for="TypeOfContact"
                           value="Yes"
                           type="radio"
                           class="input-radio"
                           checked />Yes
                </label>
                <label>
                    <input asp-for="TypeOfContact"
                           value="No"
                           type="radio"
                           class="input-radio" />No
                </label>

            </div>

        </div>

        <button type="button" class="accordion">Activity</button>
        <div class="panel">
            <h6>Activity</h6>
            <textarea id="comments"
                      class="input-textarea"
                      asp-for="Activity"></textarea>

            <div class="form-group">


                <h6>Any Barrierss Identified</h6>
                <label>
                    <input asp-for="AnyBarrierssIdentified"
                           value="Yes"
                           type="radio"
                           class="input-radio"
                           checked />Yes
                </label>
                <label>
                    <input asp-for="AnyBarrierssIdentified"
                           value="No"
                           type="radio"
                           class="input-radio" />No
                </label>

            </div>

            <h6>If yes list barriers identifieed</h6>
            <textarea id="comments"
                      class="input-textarea"
                      asp-for="If_yes_list_barriers_identifieed"></textarea>

            <h6>Step taken to Address beriers</h6>
            <textarea id="comments"
                      class="input-textarea"
                      asp-for="Step_taken_to_Address_beriers"></textarea>

            <h6>Duration</h6>
            <label id="name-label" asp-for="Duration">Duration</label>
            <input type="text"
                   asp-for="Duration"
                   id="name"
                   class="form-control"
                   required />

            <div class="form-group">
                <p>Completion & Sign-off</p>
                <label id="name-label" asp-for="StaffName">Staff Member Name</label>
                <input type="text"
                       asp-for="StaffName"
                       id="name"
                       class="form-control"
                       placeholder="Select Staff"
                       required />
            </div>
        </div>
        <button type="submit" id="submit" class="submit-button">
            Submit
        </button>

        <script type="text/javascript">
            const projectName = 'survey-form';

        </script>
    </form>
</div>

MVC_DynamicMenu/Views/SLES/ViewSLES.cshtml
@model MVC_DynamicMenu.Models.AddNewSLESProgress
@{
    ViewData["Title"] = "Home page";
}
<head>
    <link href="~/css/Addfile.css" rel="stylesheet" />
</head>
<div class="container">
    <header class="header">
        <h1 id="title" class="text-center">Add New SLES Progress</h1>
        <p id="description" class="description text-center">

        </p>
    </header>
    <form asp-action="" id="survey-form">
        <div class="form-group">
            <label id="name-label" asp-for="Client">Participant</label>
            <input type="text"
                   asp-for="Client"
                   id="name"
                   readonly
                   class="form-control"
                   placeholder="Enter your name"
                   required />


        </div>
        @*Date Start*@
        <label asp-for="EntryDate">Entry Date</label>
        <input type="date" asp-for="EntryDate" id="dateofbirth">

        @*Hierarchy Start*@
        <div class="form-group">
            <p>Hierarchy</p>
            <select id="dropdown" asp-for="Hierarchy" class="form-control" required>
                @*<option disabled selected value>Select current role</option>*@
                <option value="student">New</option>
                <option value="job">Full Time Job</option>
                <option value="learner">Full Time Learner</option>
                <option value="preferNo">Prefer not to say</option>
                <option value="other">Other</option>
            </select>
        </div>

        <label asp-for="Date">Date</label>
        <input type="date" asp-for="Date" id="dateofbirth">
        <button type="button" class="accordion">Type of Contact</button>
        <div class="panel">
            <div class="form-group">


                <h6>Type Of Contact</h6>
                <label>
                    <input asp-for="TypeOfContact"
                           value="Yes"
                           type="radio"
                           class="input-radio"
                           checked />Yes
                </label>
                <label>
                    <input asp-for="TypeOfContact"
                           value="No"
                           type="radio"
                           class="input-radio" />No
                </label>

            </div>

        </div>

        <button type="button" class="accordion">Activity</button>
        <div class="panel">
            <h6>Activity</h6>
            <textarea id="comments"
                      class="input-textarea"
                      asp-for="Activity"></textarea>

            <div class="form-group">


                <h6>Any Barrierss Identified</h6>
                <label>
                    <input asp-for="AnyBarrierssIdentified"
                           value="Yes"
                           type="radio"
                           class="input-radio"
                           checked />Yes
                </label>
                <label>
                    <input asp-for="AnyBarrierssIdentified"
                           value="No"
                           type="radio"
                           class="input-radio" />No
                </label>

            </div>

            <h6>If yes list barriers identifieed</h6>
            <textarea id="comments"
                      class="input-textarea"
                      asp-for="If_yes_list_barriers_identifieed"></textarea>

            <h6>Step taken to Address beriers</h6>
            <textarea id="comments"
                      class="input-textarea"
                      asp-for="Step_taken_to_Address_beriers"></textarea>

            <h6>Duration</h6>
            <label id="name-label" asp-for="Duration">Duration</label>
            <input type="text"
                   asp-for="Duration"
                   id="name"
                   class="form-control"
                   required />

            <div class="form-group">
                <p>Completion & Sign-off</p>
                <label id="name-label" asp-for="StaffName">Staff Member Name</label>
                <input type="text"
                       asp-for="StaffName"
                       id="name"
                       class="form-control"
                       placeholder="Select Staff"
                       required />
            </div>
        </div>
       

        <script type="text/javascript">
            const projectName = 'survey-form';

        </script>
    </form>
</div>