MVC_DynamicMenu/Controllers/NewIncidentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC_DynamicMenu.Models;
using MVC_DynamicMenu.Repo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_DynamicMenu.Controllers
{
    public class NewIncidentController : Controller
    {
        private readonly NewIncidentRepo _incidentRepo = null;

        public NewIncidentController(NewIncidentRepo incidentRepo)
        {
            _incidentRepo = incidentRepo;
        }
        public IActionResult Index()
        {
            return View();
        }
        public void setSession(int id)
        {
            var newUser = _incidentRepo.getUserById(id);
            HttpContext.Session.SetString("loggedname", newUser.Client);
        }
        public ViewResult AddNewIncident()
        {
            return View();
        }
        [HttpPost]

        public ActionResult AddNewIncident(NewIncidentLog incident)
        {
            _incidentRepo.AddNewIncident(incident);
            return RedirectPermanent("/NewIncident/Incident");
        }

        public ViewResult Incident()
        {
            HttpContext.Session.SetString("incident", _incidentRepo.GetPatients());
            List<NewIncidentLog> newincident = _incidentRepo.getAllActiveLog();
            List<IncidentLog> incident = new List<IncidentLog>();

            foreach (var item in newincident)
            {
                IncidentLog incident1 = new IncidentLog
                {
                   Client = item.Client,
                   ClientID = item.ClientID,
                   EntryDate = item.EntryDtae,
                   LastUpdate = item.EntryDtae,
                   Unit = "Counceling"
                };
                incident.Add(incident1);
            }

            return View(incident);
        }

        [HttpGet]
        public ViewResult UpdateIncident(int id)
        {
            NewIncidentLog incident = _incidentRepo.getUserById(id);
            return View(incident);
        }

        [HttpGet]
        public ViewResult ViewIncident(int id)
        {
            NewIncidentLog incident = _incidentRepo.getUserById(id);
            return View(incident);
        }

        [HttpGet]
        public ActionResult DeleteIncident(int id)
        {
            _incidentRepo.DeleteInceident(id);
            return RedirectPermanent("/NewIncident/Incident");
        }

        [HttpPost]
        public ActionResult UpdateIncident(NewIncidentLog model)
        {
            _incidentRepo.UpdateIncident(model);
            return RedirectPermanent("/NewIncident/Incident");
        }
    }
}

MVC_DynamicMenu/Views/NewIncident/Incident.cshtml
@model List<IncidentLog>
@{
    ViewData["Title"] = "Home page";
}
<head>
    <link href="~/css/Addfile.css" rel="stylesheet" />
</head>
<div class="container">
    <header class="header">
        <div class="text-right">
            <button type="button" onclick='window.location.href = "/NewIncident/AddNewIncident"' class="btn btn-primary">+New Entry</button>
        </div>
        <h1 id="title" class="text-center">Add A New Incident Log</h1>
        <p id="description" class="description text-center">

        </p>
    </header>
    <form id="survey-form">
        <div class="form-group">
            <label id="name-label" for="name">Select Participant</label>
            <input type="text"
                   name="name"
                   id="myInput"
                   class="form-control"
                   placeholder="Enter name"
                   onkeyup="myFunction()"
                   required />
        </div>

        @*Date Start*@
        <label for="dateofbirth"></label>
        <input type="date" name="dateofbirth" id="dateofbirth">
        @*Date Start*@
        <label for="dateofbirth"></label>
        <input type="date" name="dateofbirth" id="dateofbirth">

        @*Hierarchy Start*@
        <div class="form-group">
            <p>Please Select a State</p>
            <select id="dropdown" name="role" class="form-control" required>
                @*<option disabled selected value>Select current role</option>*@
                <option value="student">ACT</option>
                <option value="job">NSW</option>
                <option value="learner">VIC</option>
                <option value="student">QLD</option>
                <option value="job">SA</option>
                <option value="learner">WA</option>
                <option value="job">TAS</option>
                <option value="learner">NTA</option>
            </select>
        </div>

        <div class="row" style="overflow-x:auto;">
            <div class="col-md-12">
                <table class="table badge-light">
                    <thead>
                        <tr>
                            <th>Reference</th>
                            <th>Participent</th>
                            <th>Unity</th>
                            <th>Entry Data</th>
                            <th>Last Uplod</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ClientID</td>
                            <td>@item.Client</td>
                            <td>@item.Unit</td>
                            <td>@item.EntryDate</td>
                            <td>@item.EntryDate</td>
                            <td>
                                <a asp-controller="NewIncident" asp-action="ViewIncident" asp-route-id="@item.ClientID">View</a>
                                <a asp-controller="NewIncident" asp-action="UpdateIncident" asp-route-id="@item.ClientID">Update</a>
                                <a asp-controller="NewIncident" asp-action="DeleteIncident" asp-route-id="@item.ClientID">Delete</a>
                            </td>
                        </tr>

                    }

                </table>
            </div>
        </div>

        <script type="text/javascript">
            const projectName = 'survey-form';

        </script>

        @section Scripts{
            <script>
                function myFunction() {
                    var input, filter, table, tr, td, i, txtValue;
                    input = document.getElementById("myInput");
                    filter = input.value.toUpperCase();
                    table = document.getElementById("myTable");
                    tr = table.getElementsByTagName("tr");
                    for (i = 0; i < tr.length; i++) {
                        td = tr[i].getElementsByTagName("td")[1];
                        if (td) {
                            txtValue = td.textContent || td.innerText;
                            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                tr[i].style.display = "";
                            } else {
                                tr[i].style.display = "none";
                            }
                        }
                    }
                }
            </script>


        }
    </form>